org.gradle.jvmargs=-Xmx6G
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.2
mod_version=0.9.0
maven_group=dev.creoii.creoapi
fabric_version=0.102.1

creo-block-api-version=0.2.4
creo-block-injection-api-version=0.1.1
creo-content-modification-api-version=0.4.0
creo-convention-tags-version=0.4.0
creo-entity-attributes-version=0.2.1
creo-entity-block-collision-api-version=0.1.3
creo-events-version=0.6.0
creo-item-api-version=0.4.1
creo-registry-api-version=0.0.2
creo-shader-interaction-api-version=0.2.1
creo-worldgen-version=0.1.5

# https://modmuss50.me/fabric.html
